media: assets/images

content: 
  - name: blog
    label: Blog posts
    path: content/blog
    type: collection
    exclude: [ _index.md ]
    fields: 
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: author
        label: Author
        type: string
      - name: body
        label: Body
        type: rich-text