baseURL = 'https://leolapointe.github.io/BlogPsy/'
languageCode = 'fr-ca'
title = 'Blog Léo-Paul Lapointe 🍐'
theme = 'hugo-bearblog'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true
